---
kind: pipeline
type: docker
name: build-image

node:
    m_name: beef-ci

steps:
    - name: build-docker-image
      image: docker:dind
      pull: always
      environment:
          # _DOCKER_BUILD_IMAGE: "docker.tethys.ji0.li/allypost/twitshot"
          _DOCKER_BUILD_IMAGE: "index.docker.io/allypost/twitshot"
          _DOCKER_USERNAME:
              from_secret: DOCKER_HUB_USERNAME
          _DOCKER_PASSWORD:
              from_secret: DOCKER_HUB_PASSWORD
      commands:
          - echo "Building '$_DOCKER_BUILD_IMAGE:${DRONE_COMMIT_SHA}' on '${DRONE_STAGE_MACHINE}'"
          - docker build -t "$_DOCKER_BUILD_IMAGE":latest -t "$_DOCKER_BUILD_IMAGE":"${DRONE_COMMIT_SHA}" .
          - docker login -u "$_DOCKER_USERNAME" -p "$_DOCKER_PASSWORD"
          - docker push --all-tags "$_DOCKER_BUILD_IMAGE"
          - docker image rm "$_DOCKER_BUILD_IMAGE:${DRONE_COMMIT_SHA}"
      volumes:
          - name: docker
            path: /var/run/docker.sock

    - name: notify-watchtower
      image: alpine
      environment:
          _WATCHTOWER_DOMAIN:
              from_secret: watchtower_domain
          _WATCHTOWER_KEY:
              from_secret: watchtower_key
      commands:
          - apk add curl
          - 'curl -sL -H "Authorization: Bearer $_WATCHTOWER_KEY" "$_WATCHTOWER_DOMAIN/v1/update"'

    - name: notify-telegram
      image: appleboy/drone-telegram
      settings:
          token:
              from_secret: telegram_token
          to:
              from_secret: telegram_to
          format: MarkdownV2
          template_vars:
              machine: ${DRONE_STAGE_MACHINE}
          message: >
              *Repo:* `{{repo.name}}`


              {{#success build.status}}*✅ SUCCESS* for{{else}}*❌ FAILED*{{/success}} build {{build.number}}

              Built on `{{tpl.machine}}` in {{since build.started}}


              Commit by `{{commit.author}}` on `{{commit.branch}}`:

              ```
              {{commit.message}}
              ```


              [Link to build]({{ build.link }})
              \
              [Link to commit]({{ commit.link }})

      when:
          status:
              - success
              - failure
volumes:
    - name: docker
      host:
          path: /var/run/docker.sock

trigger:
    branch:
        - main
    event:
        - push
