version: '3'

services:
  app:
    environment:
      PORT: 8000
      HOST: "0.0.0.0"
      REDIS_URL: "redis://redis-store:6379/3"
    ports:
      - "8600:8000"
    depends_on:
      - redis-store

  redis-store:
    image: redis:alpine
